from transformers import pipeline

sentiment_pipeline = pipeline("sentiment-analysis")
data = ["It's a little tough, but in lecture, they go into the extent of Flask code you need for the class. You're not immediately dropped into creating a project from scratch; the labs are really well-documented for walk throughs on setting up your project and getting you into most of the languages, and especially for SQL. They also link you to some w3 documents, which are both comprehensive and easy to understand. Piazza is particularly helpful for asking language-specific questions if you can't easily find it on google", 
        "I will say that contrary to the other commenters I found the workload of 485 not too bad, probably similar to 281 (disclaimer -- took the class last year). I think that taking it with 370 would be reasonable. I took it with 482 and it was manageable enough (I had little free time but could continue with my clubs, also had stellar groups for both classes). YMMV but if you can find a good group for 485 I think that taking it with 370 would be perfectly fine, with a bad group I think it would be difficult but you can manage depending on your GPA standards/work tolerance.",
        "In its current state, 485 is extremely project heavy - your grade is 50 percent projects, 50 percent exams. The projects aren't anything particularly tricky, they just take time. They also require grouping up - if your partners blow, you're gonna have a rough time.",
        "Will disagree with this commenter that it's a step below 281 in terms of workload; I took it as my first ULCS alongside 376 last Winter and I had to drop because I was having a rough time (granted it was a down semester overall). If you have an excellent group that you're comfortable with it's likely completely different. HIGHLY recommend though it is such an awesome survey of EECS topics and the quintessential ULCS imo.",
        "I'm currently in 485 and 370. In my opinion 485 has a much heavier workload than 281, mainly due to the learning curve and having to self teach a bunch of new programming languages. I also personally found 281 much lighter than people make it out to be. Taking it with 370 is good tho, imo 370 is one of the lighter cs classes I've taken",
        "Only comment for this class is that I feel like theres a big disconnect between the lectures and the multiple choice questions on the exam/vagueness of wording of multiple choice questions.",
        ]
print(sentiment_pipeline(data))
